# Settings for the DiscordBot plugin.
plugin:
  # Settings for how the Discord bot, functions.
  bot:
    # The token used by the bot to access discord. Accessible at https://discord.com/developers/applications/.
    token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    # The names of the channels in which the bot should post/accept chat messages.
    botChannels:
      - speakers-of-the-gateway

    # The maximum number of users that can be queried for when searching for a user by name.
    memberQueryMax: 1

    # Configurations for the various bot extensions.
    extensions:

      # Configurations for the about extension, which gives information about the plugin.
      about:

        # Whether the extension is enabled.
        enabled: true

      # Configurations for the chat extension, which gives Minecraft chat integration.
      chat:

        # Whether the extension is enabled.
        enabled: true

      # Configurations for the IP extension, which gives the IP command.
      ip:

        # Whether the extension is enabled.
        enabled: true

        # The IP that will be displayed by the IP command.
        displayIp: 'minecraft.test:25565'

      # Configurations for the list extension, which gives information about online players.
      list:

        # Whether the extension is enabled.
        enabled: true

      # Configurations for the whitelist extension, which gives commands that manipulate the whitelist.
      whitelist:

        # Whether the extension is enabled.
        enabled: true

  # Settings for how the plugin functions on the Minecraft server.
  minecraft:

    # Used for labels and Discord mentions in-game.
    primaryColor: '#56EE5C'

    # Used for differentiated text elements and names of Discord users in-game.
    secondaryColor: '#7289DA'

    # Used for labelling configuration paths.
    tertiaryColor: '#F526ED'

    # Used for marking configurations that can be null.
    warningColor: '#EB4325'
