name: Check Pull Request

on:
    pull_request:
        branches:
            - main

        paths:
            - '**/*.kt'
            - '**/*.kts'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # https://github.com/marketplace/actions/checkout
            -   uses: actions/checkout@v3

            # https://github.com/marketplace/actions/setup-java-jdk
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: temurin

            -   name: Set gradlew execution permission
                run: chmod u+x gradlew

            # https://github.com/marketplace/actions/gradle-build-action
            -   name: Build artifacts
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: build --stacktrace

    ktlint:
        runs-on: ubuntu-latest

        steps:
            # https://github.com/marketplace/actions/checkout
            -   uses: actions/checkout@v3

            # https://github.com/marketplace/actions/ktlint-check
            -   uses: ScaCap/ktlint_version@1.4
                with:
                    ktlint_version: '0.48.0'
                    fail_on_error: true

    detekt:
        runs-on: ubuntu-latest

        steps:
            # https://github.com/marketplace/actions/checkout
            -   uses: actions/checkout@v3

            # https://github.com/marketplace/actions/run-detekt-with-reviewdog
            -   name: Run detekt with reviewdog
                uses: alaegin/Detekt-Action@v1.22.0-RC3
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    detekt_config: config/detekt/detekt.yml
                    detekt_build_upon_default_config: true
