name: Check Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin

      - name: Set gradlew Execution Permissions
        run: chmod u+x gradlew

      - name: Build Artifacts
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --stacktrace

  ktlint:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: musichin/ktlint-check@v1
        with:
          version: '0.43.2'
          annotate: true
